### ISSUE TITLE
Use the safer hiccup2.core/html to prevent XSS

### ISSUE THREAD

**Issue by Ramblurr** [whamtet/ctmx#11]
ctmx is using `hiccup.core/html` to render partial responses. `hiccup.core/html` doesn't escape strings, so it makes apps vulnerable to XSS. This is what the new ns `hiccup2.core` provides, a default that escapes strings. 

I already use `hiccup2.core/html` to render the entire pages, but during security testing I discovered that XSS can appear in rendered partials.

Here is a little workaround. It should be loaded early on during app start.

```clojure
(ns example
(:require
   [ctmx.render :as ctmx.render]
   [hiccup2.core :as hiccup2]))

;; Ensure ctmx is using the XSS safe hiccup render function
(alter-var-root #'ctmx.render/html (constantly
                                    #(-> % ctmx.render/walk-attrs hiccup2/html str)))
```

In this issue I'm not necessarily asking for the default to be changed (that might not be backwards compatible), but rather I wanted to bring it to the attention of the community.

At least I suspect some documentation is in order, and perhaps an option/toggle.

**Comment by whamtet** [comment]
Thanks @Ramblurr, we can just switch over to hiccup2.core, its fixed in 1.4.6 in clojars
