### ISSUE TITLE
Latest ctmx version in luminus template.

### ISSUE THREAD

**Issue by bobyuancn** [whamtet/ctmx#24]
here are the steps to reproduce the failure.

1. Generate a new project.

```shell
lein new luminus helloctmx +http-kit +ctmx
```

2. Run it with `lein run`. 
It works well with old version ctmx 1.4.3 in project.clj as dependency.

3. Update the ctmx version to latest 1.4.8, and re-run the project.
We see error like this:

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
        at clojure.lang.Numbers.inc(Numbers.java:139)
```

Minor version usually should be compatible, so maybe you can check on this when free, thanks!

Luminus template is having "Added +ctmx option (#544)" last year, but not listed in the table below.
https://github.com/luminus-framework/luminus-template

I think it is better add ctmx in the table if luminus template officially support it, do you think so?

**Comment by whamtet** [comment]
@bobyuancn its annoying to update the luminus demo, I explained how to run kit based demo instead in the other issue.  You can fix the bug above by going to `helloctmx.routes.home` and changing `:^int num-clicks` to `:^long num-clicks`.

**Comment by whamtet** [comment]
You're right I've messed up the semantic versioning.  Technically it should be a major version increment if I remove support for `^:int` casts.
