### ISSUE TITLE
The demo references ctmx 1.4.9, but Maven only has up to 1.4.8

### ISSUE THREAD

**Issue by ejstembler** [whamtet/ctmx#31]
The demo [references ctmx 1.4.9](https://github.com/whamtet/ctmx/blob/main/demo/project.clj#L32), but [Maven](https://mvnrepository.com/artifact/ctmx/ctmx) only has up to version 1.4.8.

Error when running `lein run` or `lein deps`:

```console
Could not find artifact ctmx:ctmx:jar:1.4.9 in central (https://repo1.maven.org/maven2/)
Could not find artifact ctmx:ctmx:jar:1.4.9 in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Comment by whamtet** [comment]
Thanks for pointing this out @ejstembler , please try again now!

**Comment by whamtet** [comment]
You're welcome.  Please let me know how if you find ctmx if you use it @ejstembler
