### ISSUE TITLE
Specifying the endpoint URL for components

### ISSUE THREAD

**Issue by michaeleverson** [whamtet/ctmx#4]
Hi there,

I was wondering what your thoughts were about being able to specify a given component's endpoint URL, so as not to clutter the top level.

The overall page might be at "www.site.com/dashboard" but the lower level components might be tucked away.

For example a table component on the 'dashboard' page might be "www.site.com/component/ui-table/table"
The row component of that table component might have an endpoint of "www.site.com/component/ui-table/row"

Is this something that is possible now, or would I need to do some tweaking?

**Comment by whamtet** [comment]
Right now the endpoint is just the component name however this is a good idea.  You could specify the url with optional metadata.  Would you like to submit a PR?

**Comment by whamtet** [comment]
Hi Michael,

Right now the routing is two tier.  The page url is defined by `make-routes`.  So in the canonical example

```clojure
(defcomponent ^:endpoint hello [req my-name]
  [:div#hello "Hello " my-name])

(make-routes
  "/demo"
  (fn [req]
    ;; page renders the hiccup and returns a ring response
    (page
      [:div
       [:label "What is your name?"]
       [:input {:name "my-name" :hx-patch "hello" :hx-target "#hello"}]
       (hello req "")])))
```

The page will be "www.site.com/demo/" and the url for updates will be "www.site.com/demo/hello".  Provided that the page ends with a trailing slash you just use relative urls.  So in the above code `:hx-patch "hello"` will actually point to `/demo/hello`.  I prefer not to add deeper nesting as it keeps things simple.  You just have to avoid reusing component names for each component on a given page, but on different pages its fine.

The caveat is that all pages must end with a slash to make the relative links work.  Ctmx will automatically redirect, but there is a small problem with this that I need to fix, so thanks for raising this point.

**Comment by michaeleverson** [comment]
Thanks for the reply. I got my wires a little crossed 😉

So the behaviour is, in the case of a shared component used in multiple pages, the component would be accessible via multiple routes: one route under each page.

**Comment by whamtet** [comment]
Correct.
