### ISSUE TITLE
How to choose routes?

### ISSUE THREAD

**Issue by ieugen** [whamtet/ctmx#8]
I'm trying to migrate this project https://github.com/rajasegar/htmx-calendar/ to ctmx to better understand the library and tech stack. 

I got this working https://github.com/ieugen/jlp/ . 

I know that `make-routes` builds the routes for me, but it also hides stuff from me.
I am new to all the stack so I might not make sense. 

How can I have routes like this?

```
(defn calendar-routes []
  (ctmx/make-routes
   "/"
   (fn [req]
     (html5-response
      (calendar req))))
  [(ctmx/make-routes
    "/next"
    (fn [req]
      (markup req (-> (LocalDate/now) (.plusDays 1)))))
   (ctmx/make-routes
    "/previous"
    (fn [req]
      (markup req (-> (LocalDate/now) (.minusDays 1)))))])
```

**Comment by whamtet** [comment]
You only need a single call to `make-routes` for each page.  In your case `next` and `previous` are not called during the initial render.  Thus we put them in the body of `calendar` so that ctmx knows to include them as endpoints.  Does that make sense?  Merge my PR and you'll see how to do it.

**Comment by ieugen** [comment]
Thanks, that solved the issue!

> Does that make sense? 

Not completely since I don't know what the macro is working.
I would like to know more for example on what paths it will mount the `next`  `previous` endpoins if we mount calendar on another path. 
I can test of course, but the behavior is not specified. I presume it will mount `next` and `previous` at the same level as `calendar` . 

The fix ntroduced another issue / confusion. 

The function name `next` conflics with `clojure.core/next` . 
```
WARNING: next already refers to: #'clojure.core/next in namespace: jlp.routes.calendar, being replaced by: #'jlp.routes.calendar/next
```
I can fix this easily by renaming the hx-get path + component to `next-month` . 

But the other part comes to mind. 
What if I can't rename that (for whatever reason). 

Is there a way to make `(ctmx/defcomponent ^:endpoint next [req]`  generate a route for `/next-month` ? 
Right now the question is mostly academic. 
I guess it makes sense only if we have a UI for which we need to make a clojure backend with ctmx.

**Comment by whamtet** [comment]
It will generate all endpoints that each defcomponent refers to recursively provided that they have the ^:endpoint metadata.  They will all be nested to the same level.  As you mention you could theoretically have a different endpoint to the component name but I prefer to keep things simple.
